// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/12/2025, 7:43:26 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/plugins/**/*.{js,ts,mjs}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/composables/**/*.{js,ts,mjs}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/utils/**/*.{js,ts,mjs}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/app.config.{js,ts,mjs}","/Users/raymon.epping/Documents/VSC/MacOS_Environment/books_library/frontend/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;